version: "3.7"

services:
  v1-web:
    command: pipenv run python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ${DEV_V1_DIR}/hyperqube:/app/hyperqube
  v1-worker:
    command: pipenv run python3 manage.py rqworker default deep_clone linked_clone
    volumes:
      - ${DEV_V1_DIR}/hyperqube:/app/hyperqube
  v2-api:
    build:
      context: ${DEV_V2_API_DIR}
      dockerfile: ./docker/dev.Dockerfile
    image: "ghcr.io/hyperqube-io/v2-api:local"
    volumes:
      - ${DEV_V2_API_DIR}/src:/src
  v2-web:
    image: alpine:latest
    command: tail -f /dev/null
  nginx:
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
