version: "3.7"

services:
  v1-web:
    command: pipenv run python3 manage.py runserver 0.0.0.0:8000
    environment:
      LICENSE_SERVICE_URL: https://license.beta.service.hyperqube.io
    volumes:
      - ${DEV_V1_DIR}/hyperqube:/app/hyperqube
      - ${DEV_V1_DIR}/scripts:/app/scripts
  v1-worker:
    command: python3 ./scripts/workers.py
    volumes:
      - ${DEV_V1_DIR}/hyperqube:/app/hyperqube
      - ${DEV_V1_DIR}/scripts:/app/scripts
  v2-api:
    build:
      context: ${DEV_V2_API_DIR}
      dockerfile: ./docker/dev.Dockerfile
    image: "ghcr.io/hyperqube-io/v2-api:local"
    volumes:
      - ${DEV_V2_API_DIR}/package.json:/package.json
      - ${DEV_V2_API_DIR}/yarn.lock:/yarn.lock
      - ${DEV_V2_API_DIR}/src:/src
  v2-web:
    image: alpine:latest
    command: tail -f /dev/null
  nginx:
    logging:
      driver: none
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
